config/routes.rb
Rails.application.routes.draw do

  root   'films#index'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'newfilm'   => 'films#new'
  post 'newfilm'  => 'films#create'
  delete 'deletefilm' => 'films#destroy'

  get 'reservationnew' => 'reservations#new'
  post 'reservationnew' => 'reservations#create'
  get 'reservationshow' => 'reservations#show'
  get 'selectseats' => 'reservations#new_select_seats'
  post 'selectseats' => 'reservations#new_select_seats'
  get 'adduserinfo' => 'reservations#add_user_info'
  post 'adduserinfo' => 'reservations#add_user_info'

  post 'filmreschedule' => 'films#reschedule'
  post 'deleteoldfilms' => 'films#delete_old_films'

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	has_one :running_film
	serialize :seats, Array

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def new
  	@reservation = Reservation.new
    @film_id = RunningFilm.find(params[:id]).film.id
    @film = Film.find(@film_id)
  	@rf = RunningFilm.where(:film_id=>@film_id).where("time > ?", Time.now.to_i.to_s)
  end

  def new_select_seats
    @reservation = Reservation.new
    @reservation.seats = RunningFilm.find(params[:reservation][:running_film_id]).seats
    @reservation.running_film_id = params[:reservation][:running_film_id]
  end

  def add_user_info
    if (params[:reservation_seats].values.split[0].map{|a| a.to_i} == [0]*100)
      redirect_to root_url
    else
      @seats = params[:reservation_seats].values
      @running_film_id = params[:reservation_rf_id]
      @user = User.new
    end
  end

  def create
    @user = User.new(nume: params[:user][:nume], email: params[:user][:email], password: "placeholder")
    if @user.save
      @running_film = RunningFilm.find(params[:reservation_rf_id])
      @running_film.seats = add_selected_seats(@running_film.seats, params[:reservation_seats].split().map{|a| a.to_i})
      
      if @running_film.save
        @reservation = Reservation.new(user_id: @user.id, running_film_id: params[:reservation_rf_id], seats: params[:reservation_seats].split().map{|a| a.to_i})
       
        if @reservation.save
          @film = Film.find(@running_film.film_id)
          @film.rank += params[:reservation_seats].split().map{|a| a.to_i}.inject(0, :+)
          print "\n\n"
          print params[:reservation_seats].split().map{|a| a.to_i}
          print "\n"
          print params[:reservation_seats].split().map{|a| a.to_i}.inject(0, :+)
          print "\n\n"
          if @film.save
           redirect_to reservationshow_path(id: @reservation.id)
          else
            redirect_to root_url
          end
        else
          redirect_to root_url
        end
      else 
        redirect_to root_url
      end
    else
      redirect_to root_url
    end
  end

  def show
    print params
    @reservation = Reservation.find(params[:id])
    @user = User.find(@reservation.user_id)
    @running_film = RunningFilm.find(@reservation.running_film_id)
    @film = Film.find(@running_film.film_id)
  end

  private

    def reservation_params
      params.require(:reservation).permit( :running_film_id )
    end


    def add_selected_seats(a, b)
      result = []
      (0..a.length-1).each do |i|
        result.append((a[i].to_i + b[i].to_i))
      end
      return result
    end

end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/add_user_info.html.erb
<h1>Rezervare: introdu datele tale</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= form_for(@user, url: reservationnew_path) do |f| %>
	  <%= f.label :nume %>
      <%= f.text_field :nume, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= hidden_field_tag "reservation_rf_id", @running_film_id %>
      <%= hidden_field_tag "reservation_seats", @seats %>
      <%= f.submit "Rezerva" %>
  <% end %>
  </div>
</div>

app/views/reservations/new.html.erb
<h1>Rezervare: selecteaza data si ora filmului</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  Film: <%= @film.title %> <br><br>
	<%= form_for(@reservation, url: selectseats_path) do |f| %>
		<%= f.label "Data si ora" %>
		<%= f.collection_select(:running_film_id, @rf, :id, :date_time) %>

		<%= f.submit "Pasul urmator" %>
	<% end %>
  </div>
</div>

app/views/reservations/new_select_seats.html.erb
<h1>Rezervare: selecteaza locurile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  *Legenda: locurile insemnate cu X sunt deja rezervate<br>
  <%= form_for(@reservation, url: adduserinfo_path) do |f| %>
  <table>
  		<thead>----------[Ecran]----------</thead>
  		<tbody>
  		<% (0..9).each do |irow| %>
  		<tr>
  			<td><%= irow+1 %>.</td>
  			<% (0..9).each do |icolumn| %>
  				<td style="width:15px"><%= hidden_field_tag "reservation_seats[" + (irow*10 + icolumn).to_s + "]", '0' %>
  				<% if @reservation.seats[irow*10 + icolumn]==0 %>
  					<%= check_box_tag "reservation_seats[" + (irow*10 + icolumn).to_s + "]", '1' %>
  				<% else %>
  					X
  				<% end %>
  			<% end %>
  			</td>
  		</tr>
  		<% end %>
  		</tbody>
  </table>
  <%= hidden_field_tag "reservation_rf_id", @reservation.running_film_id %>
  <%= f.submit %>
  <% end %>
  </div>
</div>

app/views/reservations/show.html.erb
<h1>Confirmare rezervare</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  Nume: <%= @user.nume %> <br>
  Film: <%= @film.title %> <br>
  Date: <%= Time.at(@running_film.time.to_i).to_datetime %> <br><br>
  </div>
  <div class="col-md-6 col-md-offset-3">
  Locuri(R = rezervat):<br>
  		<% (0..9).each do |irow| %>
  			<% (0..9).each do |icolumn| %>
  				<% if @reservation.seats[irow*10 + icolumn]==0 %>
  					O
  				<% else %>
  					R
  				<% end %>
  			<% end %>
  		<br>
  		<% end %>
  </div>
  <br>
  <div class="col-md-6 col-md-offset-3">
  <h3>Te asteptam la film!</h3>
  </div>
</div>