config/routes.rb
Rails.application.routes.draw do

  root   'films#index'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'newfilm'   => 'films#new'
  post 'newfilm'  => 'films#create'
  delete 'deletefilm' => 'films#destroy'

  get 'reservationnew' => 'reservations#new'
  post 'reservationnew' => 'reservations#create'
  get 'reservationshow' => 'reservations#show'
  get 'selectseats' => 'reservations#new_select_seats'
  post 'selectseats' => 'reservations#new_select_seats'
  get 'adduserinfo' => 'reservations#add_user_info'
  post 'adduserinfo' => 'reservations#add_user_info'

  post 'filmreschedule' => 'films#reschedule'
  post 'deleteoldfilms' => 'films#delete_old_films'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    # <%= link_to "Cinematograf", root_url, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Filme", root_url %></li>
        <% if logged_in? %>
          <li>
                <%= link_to "Log out", 'logout', method: "delete" %>
          </li>
        <% else %>
          <li><%= link_to "Admin Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cinematograf</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>